"""hazard redesign: add new fields to enterprise, batch, hazard

Revision ID: ca5186604393
Revises: e96f73a6f019
Create Date: 2026-04-15 20:23:57.534746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5186604393'
down_revision: Union[str, Sequence[str], None] = 'e96f73a6f019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('reporting_unit', sa.String(length=100), nullable=True))
    op.add_column('enterprises', sa.Column('industry_sector', sa.String(length=100), nullable=True))
    op.add_column('enterprises', sa.Column('enterprise_type', sa.String(length=50), nullable=True))
    op.add_column('hazards', sa.Column('description', sa.String(), nullable=True))
    op.add_column('hazards', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('hazards', sa.Column('inspection_method', sa.String(length=50), nullable=True))
    op.add_column('hazards', sa.Column('inspector', sa.String(length=100), nullable=True))
    op.add_column('hazards', sa.Column('inspection_date', sa.Date(), nullable=True))
    op.add_column('hazards', sa.Column('judgment_basis', sa.String(length=500), nullable=True))
    op.add_column('hazards', sa.Column('violation_clause', sa.String(), nullable=True))
    op.add_column('hazards', sa.Column('is_rectified', sa.String(length=20), nullable=True))
    op.add_column('hazards', sa.Column('rectification_date', sa.Date(), nullable=True))
    op.add_column('hazards', sa.Column('rectification_responsible', sa.String(length=200), nullable=True))
    op.add_column('hazards', sa.Column('rectification_measures', sa.String(), nullable=True))
    op.add_column('hazards', sa.Column('report_remarks', sa.String(), nullable=True))
    op.alter_column('hazards', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # Migrate existing content to description
    op.execute("UPDATE hazards SET description = content WHERE description IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hazards', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('hazards', 'report_remarks')
    op.drop_column('hazards', 'rectification_measures')
    op.drop_column('hazards', 'rectification_responsible')
    op.drop_column('hazards', 'rectification_date')
    op.drop_column('hazards', 'is_rectified')
    op.drop_column('hazards', 'violation_clause')
    op.drop_column('hazards', 'judgment_basis')
    op.drop_column('hazards', 'inspection_date')
    op.drop_column('hazards', 'inspector')
    op.drop_column('hazards', 'inspection_method')
    op.drop_column('hazards', 'category')
    op.drop_column('hazards', 'description')
    op.drop_column('enterprises', 'enterprise_type')
    op.drop_column('enterprises', 'industry_sector')
    op.drop_column('batches', 'reporting_unit')
    # ### end Alembic commands ###
