"""add enterprise region address contact_person

Revision ID: e96f73a6f019
Revises: 5710257e4dac
Create Date: 2026-04-15 00:44:39.877332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96f73a6f019'
down_revision: Union[str, Sequence[str], None] = '5710257e4dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('enterprises', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('enterprises', sa.Column('contact_person', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprises', 'contact_person')
    op.drop_column('enterprises', 'address')
    op.drop_column('enterprises', 'region')
    # ### end Alembic commands ###
