"""Photo upload and image serving endpoints.

Image URLs are signed with a short-lived HMAC token instead of carrying
the user's JWT. The signed URL is generated by the server when the
photo metadata is returned (e.g. on upload, on review detail load) and
lasts ``PHOTO_SIGNATURE_TTL`` seconds (default 15 minutes). This avoids
leaking JWTs to browser history, server access logs, and the
``Referer`` header.

For the deprecation window the ``?token=<jwt>`` query parameter is
still accepted, but responses from the legacy path carry
``X-Photo-Auth-Deprecated: true`` so the client side can be updated.
"""
from uuid import UUID, uuid4
import io
from datetime import datetime
from zoneinfo import ZoneInfo

from fastapi import APIRouter, Depends, File, HTTPException, Response, UploadFile, status
from PIL import Image
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.database import get_db
from app.core.security import decode_access_token
from app.core.url_signer import sign_photo_url, verify_photo_signature
from app.dependencies.auth import get_current_active_user
from app.models import Photo, TaskHazard, User
from app.schemas import PhotoBindRequest, PhotoUploadResponse
from app.services.storage_service import StorageService


def _is_jpeg(header: bytes) -> bool:
    return header.startswith(b"\xff\xd8\xff")


def _is_png(header: bytes) -> bool:
    return header.startswith(b"\x89PNG\r\n\x1a\n")


def _detect_image_format(header: bytes) -> str | None:
    if _is_jpeg(header):
        return "jpeg"
    if _is_png(header):
        return "png"
    return None


router = APIRouter()

MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB
ALLOWED_MIME_TYPES = {"image/jpeg", "image/png"}


@router.post("/upload", response_model=PhotoUploadResponse)
async def upload_photo(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    content = await file.read()
    if len(content) > MAX_FILE_SIZE:
        raise HTTPException(status_code=400, detail="File size exceeds 10MB limit")

    if file.content_type not in ALLOWED_MIME_TYPES:
        raise HTTPException(status_code=400, detail=f"Invalid file type: {file.content_type}")

    detected = _detect_image_format(content[:8])
    if detected not in ("jpeg", "png"):
        raise HTTPException(status_code=400, detail="File header does not match allowed image formats")

    try:
        img = Image.open(io.BytesIO(content))
        img.verify()
        img = Image.open(io.BytesIO(content))
        width, height = img.size
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid image file")

    if width < 100 or height < 100 or width > 8192 or height > 8192:
        raise HTTPException(status_code=400, detail=f"Image dimensions out of allowed range: {width}x{height}")

    storage = StorageService()
    temp_token = str(uuid4())
    original_path, thumbnail_path = await storage.upload_image(
        content=content,
        filename=file.filename or "image.jpg",
        temp_token=temp_token,
    )

    photo = Photo(
        temp_token=temp_token,
        original_path=original_path,
        thumbnail_path=thumbnail_path,
        file_size=len(content),
        mime_type=file.content_type,
        width=width,
        height=height,
    )
    db.add(photo)
    await db.commit()
    await db.refresh(photo)

    return PhotoUploadResponse(
        temp_token=temp_token,
        original_url=sign_photo_url(photo.id, "original"),
        thumbnail_url=sign_photo_url(photo.id, "thumbnail"),
        width=width,
        height=height,
        file_size=len(content),
    )


@router.post("/{temp_token}/bind")
async def bind_photo(
    temp_token: str,
    data: PhotoBindRequest,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    result = await db.execute(select(Photo).where(Photo.temp_token == temp_token))
    photo = result.scalar_one_or_none()
    if not photo:
        raise HTTPException(status_code=404, detail="Photo not found")

    photo.task_hazard_id = data.task_hazard_id
    photo.temp_token = None
    await db.commit()
    return {"message": "Photo bound successfully"}


@router.get("/{photo_id}/image")
async def get_photo_image(
    photo_id: UUID,
    size: str = "original",
    sig: str | None = None,
    exp: int | None = None,
    token: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """Serve a photo. Two auth modes are accepted during the migration:

    1. ``?sig=<hmac>&exp=<unix>`` - the new signed-URL mode. This is the
       default and the only mode that should remain after the deprecation
       window.
    2. ``?token=<jwt>`` - legacy mode, requires the user's JWT. Response
       carries ``X-Photo-Auth-Deprecated: true`` so the client knows to
       move to the signed mode.
    """
    if size not in ("original", "thumbnail"):
        raise HTTPException(status_code=400, detail="Invalid size parameter")

    legacy_used = False
    if sig and exp is not None:
        if not verify_photo_signature(photo_id, size, sig, exp):
            raise HTTPException(status_code=403, detail="Invalid or expired photo signature")
    elif token:
        payload = decode_access_token(token)
        if payload is None or payload.get("sub") is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        # Also confirm the owning user is still active and not soft-deleted.
        # A token issued before disable/delete used to remain valid for
        # photos until its 8h expiry.
        user_id = payload["sub"]
        owner = await db.execute(
            select(User).where(
                User.id == user_id,
                User.is_active.is_(True),
                User.deleted_at.is_(None),
            )
        )
        if owner.scalar_one_or_none() is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        legacy_used = True
    else:
        raise HTTPException(status_code=401, detail="Photo access requires a signed URL or bearer token")

    result = await db.execute(
        select(Photo).where(Photo.id == photo_id, Photo.deleted_at.is_(None))
    )
    photo = result.scalar_one_or_none()
    if not photo:
        raise HTTPException(status_code=404, detail="Photo not found")

    if photo.task_hazard_id is not None:
        th_result = await db.execute(
            select(TaskHazard)
            .where(TaskHazard.id == photo.task_hazard_id)
            .options(selectinload(TaskHazard.task))
        )
        task_hazard = th_result.scalar_one_or_none()
        if task_hazard and task_hazard.task and task_hazard.task.status != "cancelled":
            pass
        else:
            raise HTTPException(status_code=404, detail="Photo not found")
    elif photo.temp_token is None:
        raise HTTPException(status_code=404, detail="Photo not found")

    object_name = photo.original_path if size == "original" else photo.thumbnail_path
    storage = StorageService()
    try:
        content = storage.get_file_content(object_name)
    except Exception:
        raise HTTPException(status_code=404, detail="Image file not found in storage")

    content_type = photo.mime_type or "image/jpeg"
    headers = {"Cache-Control": "private, max-age=300"}
    if legacy_used:
        headers["X-Photo-Auth-Deprecated"] = "true"
    return Response(content=content, media_type=content_type, headers=headers)


@router.delete("/{photo_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_photo(
    photo_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    result = await db.execute(
        select(Photo).where(Photo.id == photo_id, Photo.deleted_at.is_(None))
    )
    photo = result.scalar_one_or_none()
    if not photo:
        raise HTTPException(status_code=404, detail="Photo not found")

    if photo.task_hazard_id is not None:
        th_result = await db.execute(
            select(TaskHazard)
            .where(TaskHazard.id == photo.task_hazard_id)
            .options(selectinload(TaskHazard.task))
        )
        task_hazard = th_result.scalar_one_or_none()
        if not task_hazard or not task_hazard.task:
            raise HTTPException(status_code=404, detail="Photo not found")
        if task_hazard.task.status != "pending":
            raise HTTPException(
                status_code=400,
                detail="Cannot delete photo from a completed or cancelled task",
            )

    # Storage first: if MinIO fails we leave the row intact so the
    # operator can retry. Once the object is gone we soft-delete the DB
    # row; if the DB write fails the file is already removed and the
    # orphan is harmless (no FK references the storage path).
    storage = StorageService()
    try:
        storage.delete_file(photo.original_path)
        storage.delete_file(photo.thumbnail_path)
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Failed to delete file from storage: {e}",
        )

    photo.deleted_at = datetime.now(ZoneInfo("Asia/Shanghai"))
    await db.commit()

    return None
