"""add batch creator and file path and hazard hash index

Revision ID: 5710257e4dac
Revises: f8bd3b56debc
Create Date: 2026-04-14 23:58:32.845794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5710257e4dac'
down_revision: Union[str, Sequence[str], None] = 'f8bd3b56debc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.add_column('batches', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('batches', sa.Column('original_file_path', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'batches', 'users', ['creator_id'], ['id'])
    op.create_index('ix_hazards_enterprise_content_hash_location_hash', 'hazards', ['enterprise_id', sa.literal_column("digest(content, 'sha256')"), sa.literal_column("digest(COALESCE(location, ''), 'sha256')")], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hazards_enterprise_content_hash_location_hash', table_name='hazards', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'original_file_path')
    op.drop_column('batches', 'creator_id')
    # ### end Alembic commands ###
