"""add_missing_columns_to_audit_logs

Revision ID: 9d12bfc4d8f0
Revises: a40bbb911dae
Create Date: 2026-04-18 19:03:40.512267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d12bfc4d8f0'
down_revision: Union[str, Sequence[str], None] = 'a40bbb911dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('path', sa.String(length=200), nullable=True))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'path')
    op.drop_column('audit_logs', 'method')
    # ### end Alembic commands ###
