"""add unique constraint on report task_id

Revision ID: a40bbb911dae
Revises: ed2048221f07
Create Date: 2026-04-16 01:37:08.386397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40bbb911dae'
down_revision: Union[str, Sequence[str], None] = 'ed2048221f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reports', ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='unique')
    # ### end Alembic commands ###
