"""add_reporting_unit_to_hazards

Revision ID: ed2048221f07
Revises: ca5186604393
Create Date: 2026-04-15 22:45:41.603090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2048221f07'
down_revision: Union[str, Sequence[str], None] = 'ca5186604393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hazards', sa.Column('reporting_unit', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hazards', 'reporting_unit')
    # ### end Alembic commands ###
