"""Add deleted_at to task_hazards

Revision ID: f7eae3e357f3
Revises: 9d12bfc4d8f0
Create Date: 2026-04-18 19:58:39.315420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7eae3e357f3'
down_revision: Union[str, Sequence[str], None] = '9d12bfc4d8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_hazards', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_hazards', 'deleted_at')
    # ### end Alembic commands ###
